#!/usr/bin/make -f

include ../utils/config.mk
objects += tp.o
objects += seg_init.o
objects += pag_init.o
objects += task.o
objects += scheduler.o
objects += syscall.o
include ../utils/rules.mk
#-include $(dependencies)
